#' Sobel test for single-mediator causal mediation analysis
#'
#' Computes the classical Sobel test for the null hypothesis of no
#' mediation effect in a single-mediator setting. The Sobel test is based
#' on the product of the exposure--mediator effect and the
#' mediator--outcome effect, and is commonly used as a benchmark method in
#' mediation analysis.
#'
#' In the large-scale mediation setting considered in the paper, Sobel's
#' test serves as a classical baseline but is known to be conservative for
#' testing the composite null hypothesis of no mediation effect.
#'
#' @param Z1 A numeric vector or scalar containing the Z-statistics for
#'   testing the exposure--mediator effect.
#' @param Z2 A numeric vector or scalar containing the Z-statistics for
#'   testing the mediator--outcome effect.
#'
#' @return
#' A numeric vector of p-values from the Sobel test.
#'
#' @details
#' The test statistic is
#' \deqn{
#' T = \frac{(Z_1 Z_2)^2}{Z_1^2 + Z_2^2},
#' }
#' and the p-value is computed from a chi-squared distribution with one
#' degree of freedom.
#'
#' @references
#' Sobel ME (1982). \emph{Asymptotic confidence intervals for indirect
#' effects in structural equation models}. In \emph{Sociological
#' Methodology}, 13, 290--312.
#'
#'
#' @export
Sobel = function(Z1,Z2){
  T = (Z1*Z2)^2/(Z1^2+Z2^2)
  stats::pchisq(T,df=1,lower.tail = F)
}

#' Product-based composite test for mediation signal detection
#'
#' Computes a product-based composite test statistic and the corresponding
#' p-values for paired effect estimates or test statistics. This function
#' can be used as a comparison method in simulation studies for
#' large-scale mediation testing.
#'
#' @param a A numeric vector containing the first set of effect estimates
#'   or test statistics, such as exposure--mediator association
#'   statistics.
#' @param b A numeric vector containing the second set of effect estimates
#'   or test statistics, such as mediator--outcome association
#'   statistics.
#' @param cdfX An optional list giving a precomputed numerical reference
#'   distribution for the product statistic, as returned by [CDF_p2()].
#'   If \code{NULL}, the reference distribution is computed internally.
#'
#' @return
#' A list with two components:
#' \describe{
#'   \item{\code{pp}}{A numeric vector of p-values.}
#'   \item{\code{zz}}{A numeric vector of signed Z-scores obtained by
#'   transforming the p-values and restoring the sign of \code{a * b}.}
#' }
#'
#' @details
#' This function forms a product-based signal measure from \code{a} and
#' \code{b}, then evaluates its significance by interpolating from a
#' numerically approximated reference distribution generated by
#' [CDF_p2()]. The returned signed Z-score is useful when downstream
#' procedures require both a significance measure and a direction.
#'
#' Although this function is not part of the main TLR procedure proposed
#' in the paper, it can be useful as an auxiliary or comparison method in
#' method evaluation.
#'
#'
#' @export
CompTestER = function(a,b,cdfX = NULL){
  ab = abs(a*b)
  var_vec = c(var(a),var(b))
  df_min = min(ab)/sqrt(max(var_vec))
  if(is.null(cdfX)){cdfX = CDF_p2(df_min, max(ab))}
  xout = ab/sqrt(sum(var_vec)-1)
  p_value = approx(x = cdfX$x, y = cdfX$y, xout = xout, yleft = 1, yright = 0, method = 'linear')$y
  return(list(pp=p_value,zz=safe_z(p_value)*sign(a*b)))
}

#' Numerical reference CDF for the product-based composite test
#'
#' Constructs a numerical approximation to the reference cumulative
#' distribution function used by [CompTestER()] for the product-based
#' composite test statistic.
#'
#' @param df_min A numeric value related to the lower end of the relevant
#'   product-statistic range.
#' @param df_max A numeric value related to the upper end of the relevant
#'   product-statistic range.
#'
#' @return
#' A list with components:
#' \describe{
#'   \item{\code{x}}{A numeric grid of evaluation points.}
#'   \item{\code{y}}{The corresponding approximated upper-tail or survival
#'   probabilities used for interpolation.}
#' }
#'
#' @details
#' The function builds a dense polynomially spaced grid and evaluates a
#' Bessel-function-based kernel to numerically approximate the reference
#' distribution used by [CompTestER()]. This is an internal computational
#' helper rather than a standalone inferential procedure.
#'
#' @keywords internal
CDF_p2 = function(df_min, df_max){
  len_x = 1e5
  max_df_prod = df_max * 2
  grid_x = poly_space(0, max_df_prod, len_x, order = 10)
  grid_y = 2 * base::besselK(grid_x, 0) / pi
  integrand = (grid_y[1:(len_x - 1)] + grid_y[2:len_x])/2 * diff(grid_x)
  int_grid_y = rev(cumsum(rev(integrand))); int_grid_y[1] = 1
  cdfX = list(x = grid_x[1:(len_x - 1)], y = int_grid_y)
  return(cdfX)
}


#' Safely transform p-values to signed Z-scale
#'
#' Converts p-values to Z-scores using the standard normal quantile
#' transformation, while capping extremely small p-values to avoid
#' numerical overflow.
#'
#' @param pp A numeric vector of p-values.
#'
#' @return
#' A numeric vector of Z-scores.
#'
#' @details
#' Extremely small p-values below machine-representable range are mapped
#' to a finite upper cap before applying [stats::qnorm()]. This helper is
#' mainly used to stabilize downstream transformations in large-scale
#' testing settings.
#'
#' @keywords internal
safe_z=function(pp){ return(ifelse(pp<8e-324,40,stats::qnorm(pp/2,lower.tail = F))) }


#' Construct a polynomially spaced numerical grid
#'
#' Generates a one-dimensional grid between two endpoints with polynomial
#' spacing, allowing denser resolution near one end of the interval.
#'
#' @param a A numeric scalar giving the left endpoint of the interval.
#' @param b A numeric scalar giving the right endpoint of the interval.
#' @param n A positive integer giving the number of grid points.
#' @param order A positive numeric value controlling the degree of
#'   polynomial spacing. Larger values concentrate more grid points near
#'   the left endpoint.
#'
#' @return
#' A numeric vector of length \code{n}.
#'
#' @details
#' This helper is used in numerical integration and interpolation steps
#' where higher grid resolution is desired in the tail region, which is
#' particularly relevant for large-scale testing problems emphasizing
#' small p-values.
#'
#' @keywords internal
poly_space = function(a, b, n, order = 1){
  k = (b - a)^(1 - order)
  linsp = pracma::linspace(a, b, n)
  return(k * (linsp - a) ^ order + a)
}
